name: Update README with YouTube Videos

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */5 * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project dependencies
        run: npm install
      - name: Update README.md file
        run: |
          node updateReadme > README.md
        env:
          YOUR_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUR_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Kabirou ALASSANE
          author_email: kabirou2001@gmail.com
          force: false
          signoff: false
          message: ' 🤖Auto: README.md updated by Quavo ❤️, my Github bot'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
