name: Update README all day at 00:00

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Kabirou ALASSANE
          author_email: kabirou2001@gmail.com
          force: false
          signoff: false
          message: 'README.md updated by Quavo ❤️'
        env:

          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
